config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers =>{:registrations => "registrations"}
    #change the route from /user/login to /login route
    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
    end
    devise_scope :user do
      get 'signup', to:'devise/registrations#new'
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :lists, only: [ :index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  belongs_to :users
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :lists
  validates :name, :username, :email, :encrypted_password, presence: true
  validates :username, length: { minimum: 4 }, uniqueness: true
  validates :encrypted_password, length: { minimum: 6}
  validate :password_requirements_are_met
  validates :email, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, message: "valid email please"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable

  private

  def password_requirements_are_met
    rules = {
      " must contain at least one lowercase letter"  => /[a-z]+/,
      " must contain at least one uppercase letter"  => /[A-Z]+/,
      " must contain at least one digit"             => /\d+/,
      " must contain at least one special character" => /[^A-Za-z0-9]+/
    }

    rules.each do |message, regex|
      errors.add( :encrypted_password, message ) unless encrypted_password.match( regex )
    end
  end
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniAuthCallbacksController
  def github
    @user =  User.from_omniauth(request.env["omniauth.auth"])
    signin_and_redirect @user
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
    @list = List.new

  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def signup_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/bookmarks/_new.html.erb
<div class="modal fade" id="add_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: 'Select a movie', input_html: { class: 'select2' } %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
      </div>
      <div class="modal-footer">
          <%= f.submit 'Add movie', class: 'btn btn-flat' %>
        <% end %>
        <button type="button" class="btn btn-cancel" data-dismiss="modal">Back</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iFilm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% unless notice.nil? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/_new.html.erb
<div class="modal fade" id="add_list_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a new list</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Thriller' %>
          <%= f.input :image_url %>
      </div>
      <div class="modal-footer">
          <%= f.submit 'Add list', class: 'btn btn-flat' %>
        <% end %>
        <button type="button" class="btn btn-cancel" data-dismiss="modal">Back</button>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="cover" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/65128/pexels-photo-65128.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)">
  <h1 class = "d-flex justify-content-center py-5">List of movies</h1>
</div>
<div class="row my-5">
  <% @lists.each do |list| %>
  <div class="col-12 col-sm-4 mb-3 d-flex justify-content-around">
    <%= link_to list_path(list), class:'text-decoration-none' do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.9), rgba(0,0,0,0.9)), url(<%= list.image_url %>)">
      <h1> <%= list.name%></h1>
    </div>
   <% end %>
 </div>
 <% end %>
</div>

<%= render 'lists/new', list: @list%>

app/views/lists/show.html.erb
<div class="navbar d-flex justify-content-end">
  <ul class="">
    <li><button type="button" class="btn btn-flat" data-toggle="modal" data-target="#add_movie_modal">
      add a movie
    </button></li>
    <li><%= link_to 'Return to movie lists', root_path, class: "btn btn-flat"%></li>
  <!-- <li><a href="#contact">Contact</a></li>
    <li><a href="#about">About</a></li> -->
  </ul>
</div>
<div class="cover" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.image_url %>">
    <h1 class="d-flex justify-content-center py-5"><%= @list.name %></h1>
</div>
<span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
<div class="container mb-5">
  <div class="d-flex justify-content-between my-3">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
  </div>
  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-3">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: 'movie-img rounded-top' %>
          <div class="rounded-bottom d-flex flex-column p-3 ">
            <strong><%= movie.title %> <span class="text-muted font-weight-lighter">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted my-2"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-2">
              <div>
                <i class="fas fa-quote-left mr-2 quote"></i><small><%= bookmark.comment %></small>
              </div>
              <small class="text-right"><%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-muted' do%>
                 <i class="far fa-trash-alt"></i>
                 <% end %>
              </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render 'bookmarks/new', list: @list %>

app/views/pages/home.html.erb
<%if current_user.nil? %>
  <section class="intro">
    <div class="inner">
        <div class="content">
          <div class="header-text">
            <section class="os-animation" data-os-animation="fadeIn" data-os-animation-delay="0.5s">
              <h3 class="p-1 mb-5 d-flex justify-content-center title">Find your favorite films, start a conversation, build a community!</h3>
            </section>
            <section class="os-animation d-flex justify-content-evenly" data-os-animation="fadeIn" data-os-animation-delay="0.7s">
              <%= link_to 'FIND OUT MORE', user_session_path, class:'btn-red-landing' %>
            </section>
          </div>
          <div>
            <%= image_tag("movie.png", class:"landing-page-img")%>
          </div>
        </div>
    </div>
  </section>
<%end%>

app/views/shared/_navbar.html.erb
<div>
  <ul class="navbar">
    <li class='title-nav'><%= link_to 'WATCHILL', root_path, class:'btn-nav' %></li>
    <% if current_user.nil? %>
      <li><%= link_to 'LOG IN', user_session_path, class:'btn-nav' %></li>
      <li><%= link_to 'SIGN UP', new_user_session_path, class:'btn-nav btn-accent' %></li>
    <% end %>
    <% if current_user %>
      <li><%= link_to 'Dashboard', user_session_path, class:'btn-nav' %></li>
      <li><button class = 'btn-nav' data-toggle="modal" data-target="#add_list_modal">+ new list</button></li>
    <% end %>
  </ul>
</div>